### ISSUE TITLE
Actividad 4 Mapa Mental_ Maribel Santiago Bautista

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-4-mapa-mental-santiagomary1004#1]
[Actividad 4 Mapa Mental_Maribel Santiago Bautista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-santiagomary1004/files/9642205/Actividad.4.Mapa.Mental_Maribel.Santiago.Bautista.pdf)

**Comment by ErikCuevas03** [comment]
18.5 faltan elementos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
